enableTelemetry: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.0-rc.5.cjs

packageExtensions:
  "react-icons@2.2.7":
    peerDependencies:
      "prop-types": "*"
  "react-docgen-typescript-loader@3.7.2":
    peerDependencies:
      "webpack": "4.41.5"
  "react-dev-utils@11.0.4":
    peerDependencies:
      "typescript": "4.4.3"
      "webpack": "5.51.1"
  "rc-trigger@2.6.5":
    peerDependencies:
      "react": "17.0.1"
      "react-dom": "17.0.1"
  "@mdx-js/loader@1.6.22":
    peerDependencies:
      "react": "17.0.1"
  "@storybook/addon-essentials@6.3.7":
    peerDependencies:
      "@storybook/components": "6.3.7"
      "@storybook/core-events": "6.3.7"
      "@storybook/theming": "6.3.7"
  "@storybook/core@6.3.7":
    peerDependencies:
      "webpack": "5.51.1"
  "@storybook/csf-tools@6.3.7":
    peerDependencies:
      "@babel/core": "7.14.6"
  "@grafana/slate-react@0.22.10-grafana":
    peerDependencies:
      "slate-react": ">=0.22.0"
  "rc-time-picker@3.7.3":
    peerDependencies:
      "react": "17.0.1"
      "react-dom": "17.0.1"
  "@storybook/core-server@6.3.7":
    peerDependencies:
      "@babel/core": "7.14.6"
  "react-resizable@3.0.4":
    peerDependencies:
      "react-dom": "17.0.1"
